export const users = [
  {
    id: 1,
    first_name: "str",
    last_name: "str",
    clubs_house: "str",
    individual_role: "str",
    projects: [
      { project_id: "int", role: "int" },
      { project_id: "int", role: "int" },
    ],
  },
  {
    id: 2,
    first_name: "str",
    last_name: "str",
    clubs_house: "str",
    individual_role: "str",
    projects: [
      { project_id: "int", role: "int" },
      { project_id: "int", role: "int" },
    ],
  },
];

export const projects = [
  {
    _id: "6358040b666905b119ba9406",
    project_id: "5447100866672",
    template_id: 2,
    project_name: "Dog and Cat Shelter Website",
    project_desciption:
      "The non-profit organisation “Adopt Happiness” takes dogs and cats from the streets and provides shelter for them until they find an ideal home for them. They recently noticed a huge interest in adoption; however, they only have a Facebook page which makes applications long and very often confusing as they need to exchange a lot of messages with potential adopters. “Adopt Happiness” is looking to have its website where it could share photos of animals that are available for adoption, including the requirements for an ideal home. In addition, every interested applicant would be able to fill out an application which would make it easier for the organization to filter out unsuitable candidates based on each animal’s needs.",
    project_status: 1,
    project_progress: 2,
    time_start: 1665884142.0026577,
    time_e: 2113418,
    time_deadline: 1667997560.0026577,
    team_size: 4,
    team_members: [
      {
        name: "Hassan Mckenzie",
        clubs_house: "Almeida",
        individual_role: "Analyst",
        role: "Scrum Master",
      },
      {
        name: "Diego Banks",
        clubs_house: "Almeida",
        individual_role: "Developer",
        role: "Product Owner",
      },
      {
        name: "Amiya Pena",
        clubs_house: "Somerville",
        individual_role: "Developer",
        role: "Tech Lead",
      },
      {
        name: "Malachi Banks",
        clubs_house: "Grace",
        individual_role: "Developer",
      },
    ],
  },
  {
    _id: "6358040b666905b119ba9407",
    project_id: "2252617344031",
    template_id: 3,
    project_name: "AND Eat",
    project_desciption:
      "Many ANDis are serious foodies. This means they often like to visit local restaurants to try out new cuisines. ANDis are also quite social so they like to be able to enjoy some equally good conversation alongside their meals.What I envisage is a portal which allows ANDis to inform other ANDis where they’re planing on going to lunch and what restaurants they recommend in the area. This portal would allow fellow foodies an opportunity to meet up and share their recommendations.",
    project_status: 2,
    project_progress: 3,
    time_start: 1665721446.0026577,
    time_e: 4965497,
    time_deadline: 1670686943.0026577,
    team_size: 4,
    team_members: [
      {
        name: "Osvaldo Mcfarland",
        clubs_house: "Grace",
        individual_role: "Developer",
        role: "Scrum Master",
      },
      {
        name: "Bruce Chang",
        clubs_house: "Somerville",
        individual_role: "Developer",
        role: "Product Owner",
      },
      {
        name: "Violet Chang",
        clubs_house: "Somerville",
        individual_role: "Analyst",
        role: "Tech Lead",
      },
      {
        name: "Amiya Tapia",
        clubs_house: "Somerville",
        individual_role: "Analyst",
      },
    ],
  },
  {
    _id: "6358040b666905b119ba9408",
    project_id: "2980614492010",
    template_id: 3,
    project_name: "AND Eat",
    project_desciption:
      "Many ANDis are serious foodies. This means they often like to visit local restaurants to try out new cuisines. ANDis are also quite social so they like to be able to enjoy some equally good conversation alongside their meals.What I envisage is a portal which allows ANDis to inform other ANDis where they’re planing on going to lunch and what restaurants they recommend in the area. This portal would allow fellow foodies an opportunity to meet up and share their recommendations.",
    project_status: 3,
    project_progress: 3,
    time_start: 1665778769.0026577,
    time_e: 2737497,
    time_deadline: 1668516266.0026577,
    team_size: 6,
    team_members: [
      {
        name: "Osvaldo Caldwell",
        clubs_house: "Almeida",
        individual_role: "Analyst",
        role: "Scrum Master",
      },
      {
        name: "Isai Banks",
        clubs_house: "Grace",
        individual_role: "Analyst",
        role: "Product Owner",
      },
      {
        name: "Violet Mckenzie",
        clubs_house: "Somerville",
        individual_role: "Developer",
        role: "Tech Lead",
      },
      {
        name: "Amiya Greer",
        clubs_house: "Somerville",
        individual_role: "Analyst",
      },
      {
        name: "Amiya Andrews",
        clubs_house: "Somerville",
        individual_role: "Analyst",
      },
      {
        name: "Violet Andrews",
        clubs_house: "Grace",
        individual_role: "Analyst",
      },
    ],
  },
  {
    _id: "6358040b666905b119ba9409",
    project_id: "1024293485206",
    template_id: 4,
    project_name: "ANDevelop Developing",
    project_desciption:
      "With the fluctuation of incoming ANDis, AND digital has been tasked with the empowerment of equipping their newcomers. Typically, this is done during build week, a period in the ANDuction to develop a project. Making these template projects takes time and recourses which could be placed elsewhere, like mentorship and other work tasks. These templates also typically require the same sort of requirements, AND Digital is looking for a platform to make a platform that makes this entire process streamlined, where users can pull projects from a template and make them down. In combination with providing their tastes and distastes; constituting feedforward for the next reiterations of build weeks.",
    project_status: 2,
    project_progress: 2,
    time_start: 1666174010.0026577,
    time_e: 4277123,
    time_deadline: 1670451133.0026577,
    team_size: 6,
    team_members: [
      {
        name: "Violet Arellano",
        clubs_house: "Somerville",
        individual_role: "Developer",
        role: "Scrum Master",
      },
      {
        name: "Kendall Banks",
        clubs_house: "Grace",
        individual_role: "Developer",
        role: "Product Owner",
      },
      {
        name: "Amiya Mckenzie",
        clubs_house: "Almeida",
        individual_role: "Analyst",
        role: "Tech Lead",
      },
      {
        name: "Jenna Gregory",
        clubs_house: "Almeida",
        individual_role: "Developer",
      },
      {
        name: "Sullivan Caldwell",
        clubs_house: "Almeida",
        individual_role: "Developer",
      },
      {
        name: "Malachi Tapia",
        clubs_house: "Almeida",
        individual_role: "Analyst",
      },
    ],
  },
  {
    _id: "6358040b666905b119ba940a",
    project_id: "4040619903824",
    template_id: 4,
    project_name: "ANDevelop Developing",
    project_desciption:
      "With the fluctuation of incoming ANDis, AND digital has been tasked with the empowerment of equipping their newcomers. Typically, this is done during build week, a period in the ANDuction to develop a project. Making these template projects takes time and recourses which could be placed elsewhere, like mentorship and other work tasks. These templates also typically require the same sort of requirements, AND Digital is looking for a platform to make a platform that makes this entire process streamlined, where users can pull projects from a template and make them down. In combination with providing their tastes and distastes; constituting feedforward for the next reiterations of build weeks.",
    project_status: 2,
    project_progress: 2,
    time_start: 1665845082.0026577,
    time_e: 5427732,
    time_deadline: 1671272814.0026577,
    team_size: 9,
    team_members: [
      {
        name: "Bruce Cantu",
        clubs_house: "Somerville",
        individual_role: "Analyst",
        role: "Scrum Master",
      },
      {
        name: "Kendall Andrews",
        clubs_house: "Almeida",
        individual_role: "Developer",
        role: "Product Owner",
      },
      {
        name: "Kendall Arellano",
        clubs_house: "Grace",
        individual_role: "Analyst",
        role: "Tech Lead",
      },
      {
        name: "Isai Mcfarland",
        clubs_house: "Somerville",
        individual_role: "Developer",
      },
      {
        name: "Diego Chang",
        clubs_house: "Grace",
        individual_role: "Developer",
      },
      {
        name: "Diego Andrews",
        clubs_house: "Somerville",
        individual_role: "Analyst",
      },
      {
        name: "King Pena",
        clubs_house: "Almeida",
        individual_role: "Developer",
      },
      {
        name: "Hassan Pena",
        clubs_house: "Grace",
        individual_role: "Analyst",
      },
      {
        name: "Osvaldo Pena",
        clubs_house: "Grace",
        individual_role: "Developer",
      },
    ],
  },
  {
    _id: "6358040b666905b119ba940b",
    project_id: "3919879219451",
    template_id: 4,
    project_name: "ANDevelop Developing",
    project_desciption:
      "With the fluctuation of incoming ANDis, AND digital has been tasked with the empowerment of equipping their newcomers. Typically, this is done during build week, a period in the ANDuction to develop a project. Making these template projects takes time and recourses which could be placed elsewhere, like mentorship and other work tasks. These templates also typically require the same sort of requirements, AND Digital is looking for a platform to make a platform that makes this entire process streamlined, where users can pull projects from a template and make them down. In combination with providing their tastes and distastes; constituting feedforward for the next reiterations of build weeks.",
    project_status: 2,
    project_progress: 1,
    time_start: 1665604172.0026577,
    time_e: 4179532,
    time_deadline: 1669783704.0026577,
    team_size: 7,
    team_members: [
      {
        name: "Malachi Pena",
        clubs_house: "Somerville",
        individual_role: "Developer",
        role: "Scrum Master",
      },
      {
        name: "Sullivan Mckenzie",
        clubs_house: "Almeida",
        individual_role: "Analyst",
        role: "Product Owner",
      },
      {
        name: "Jenna Banks",
        clubs_house: "Grace",
        individual_role: "Developer",
        role: "Tech Lead",
      },
      {
        name: "Isai Arellano",
        clubs_house: "Grace",
        individual_role: "Developer",
      },
      {
        name: "Osvaldo Tapia",
        clubs_house: "Grace",
        individual_role: "Developer",
      },
      {
        name: "Violet Mcfarland",
        clubs_house: "Grace",
        individual_role: "Developer",
      },
      {
        name: "Violet Tapia",
        clubs_house: "Grace",
        individual_role: "Analyst",
      },
    ],
  },
  {
    _id: "6358040b666905b119ba940c",
    project_id: "3410410280188",
    template_id: 2,
    project_name: "Dog and Cat Shelter Website",
    project_desciption:
      "The non-profit organisation “Adopt Happiness” takes dogs and cats from the streets and provides shelter for them until they find an ideal home for them. They recently noticed a huge interest in adoption; however, they only have a Facebook page which makes applications long and very often confusing as they need to exchange a lot of messages with potential adopters. “Adopt Happiness” is looking to have its website where it could share photos of animals that are available for adoption, including the requirements for an ideal home. In addition, every interested applicant would be able to fill out an application which would make it easier for the organization to filter out unsuitable candidates based on each animal’s needs.",
    project_status: 2,
    project_progress: 2,
    time_start: 1666505763.0036557,
    time_e: 3787151,
    time_deadline: 1670292914.0036557,
    team_size: 6,
    team_members: [
      {
        name: "Jenna Tapia",
        clubs_house: "Somerville",
        individual_role: "Analyst",
        role: "Scrum Master",
      },
      {
        name: "Violet Banks",
        clubs_house: "Almeida",
        individual_role: "Developer",
        role: "Product Owner",
      },
      {
        name: "Hassan Caldwell",
        clubs_house: "Almeida",
        individual_role: "Developer",
        role: "Tech Lead",
      },
      {
        name: "Jenna Chang",
        clubs_house: "Almeida",
        individual_role: "Developer",
      },
      {
        name: "Osvaldo Tapia",
        clubs_house: "Somerville",
        individual_role: "Developer",
      },
      {
        name: "Diego Chang",
        clubs_house: "Grace",
        individual_role: "Analyst",
      },
    ],
  },
  {
    _id: "6358040b666905b119ba940d",
    project_id: "7765422271478",
    template_id: 3,
    project_name: "AND Eat",
    project_desciption:
      "Many ANDis are serious foodies. This means they often like to visit local restaurants to try out new cuisines. ANDis are also quite social so they like to be able to enjoy some equally good conversation alongside their meals.What I envisage is a portal which allows ANDis to inform other ANDis where they’re planing on going to lunch and what restaurants they recommend in the area. This portal would allow fellow foodies an opportunity to meet up and share their recommendations.",
    project_status: 1,
    project_progress: 1,
    time_start: 1666399435.0036557,
    time_e: 2591480,
    time_deadline: 1668990915.0036557,
    team_size: 8,
    team_members: [
      {
        name: "Kendall Tapia",
        clubs_house: "Somerville",
        individual_role: "Developer",
        role: "Scrum Master",
      },
      {
        name: "Violet Gregory",
        clubs_house: "Almeida",
        individual_role: "Analyst",
        role: "Product Owner",
      },
      {
        name: "Hassan Pena",
        clubs_house: "Almeida",
        individual_role: "Analyst",
        role: "Tech Lead",
      },
      {
        name: "Malachi Arellano",
        clubs_house: "Grace",
        individual_role: "Analyst",
      },
      {
        name: "Isai Cantu",
        clubs_house: "Somerville",
        individual_role: "Developer",
      },
      {
        name: "Hassan Mckenzie",
        clubs_house: "Somerville",
        individual_role: "Analyst",
      },
      {
        name: "Malachi Greer",
        clubs_house: "Almeida",
        individual_role: "Analyst",
      },
      {
        name: "Malachi Greer",
        clubs_house: "Grace",
        individual_role: "Analyst",
      },
    ],
  },
  {
    _id: "6358040b666905b119ba940e",
    project_id: "3778229429809",
    template_id: 4,
    project_name: "ANDevelop Developing",
    project_desciption:
      "With the fluctuation of incoming ANDis, AND digital has been tasked with the empowerment of equipping their newcomers. Typically, this is done during build week, a period in the ANDuction to develop a project. Making these template projects takes time and recourses which could be placed elsewhere, like mentorship and other work tasks. These templates also typically require the same sort of requirements, AND Digital is looking for a platform to make a platform that makes this entire process streamlined, where users can pull projects from a template and make them down. In combination with providing their tastes and distastes; constituting feedforward for the next reiterations of build weeks.",
    project_status: 2,
    project_progress: 3,
    time_start: 1665665011.0036557,
    time_e: 4367888,
    time_deadline: 1670032899.0036557,
    team_size: 5,
    team_members: [
      {
        name: "Amiya Mcfarland",
        clubs_house: "Almeida",
        individual_role: "Developer",
        role: "Scrum Master",
      },
      {
        name: "Osvaldo Pena",
        clubs_house: "Somerville",
        individual_role: "Analyst",
        role: "Product Owner",
      },
      {
        name: "Kendall Caldwell",
        clubs_house: "Grace",
        individual_role: "Developer",
        role: "Tech Lead",
      },
      {
        name: "Jenna Mckenzie",
        clubs_house: "Grace",
        individual_role: "Developer",
      },
      {
        name: "Diego Mckenzie",
        clubs_house: "Grace",
        individual_role: "Developer",
      },
    ],
  },
  {
    _id: "6359075385db89faebf908d3",
    project_id: "54493008600072",
    template_id: 2,
    project_name: "Testing this post method",
    project_desciption: "This is the desc.",
    project_status: 1,
    project_progress: 2,
    time_start: 1665884142.0026577,
    time_e: 2113418,
    time_deadline: 1667997560.0026577,
    team_size: 4,
    team_members: [
      {
        name: "Hassan Mckenzie",
        clubs_house: "Almeida",
        individual_role: "Analyst",
        role: "Scrum Master",
      },
      {
        name: "Diego Banks",
        clubs_house: "Almeida",
        individual_role: "Developer",
        role: "Product Owner",
      },
      {
        name: "Amiya Pena",
        clubs_house: "Somerville",
        individual_role: "Developer",
        role: "Tech Lead",
      },
      {
        name: "Malachi Banks",
        clubs_house: "Grace",
        individual_role: "Developer",
      },
    ],
  },
];

export const templates = [
  {
    _id: "6357ee7b666905b119ba93ed",
    template_id: 4,
    template_name: "ANDevelop Developing",
    desciption:
      "With the fluctuation of incoming ANDis, AND digital has been tasked with the empowerment of equipping their newcomers. Typically, this is done during build week, a period in the ANDuction to develop a project. Making these template projects takes time and recourses which could be placed elsewhere, like mentorship and other work tasks. These templates also typically require the same sort of requirements, AND Digital is looking for a platform to make a platform that makes this entire process streamlined, where users can pull projects from a template and make them down. In combination with providing their tastes and distastes; constituting feedforward for the next reiterations of build weeks.",
    difficulty_rating: 3,
    time_esitmate: 5243558,
    team_estimate: 4,
  },
  {
    _id: "6357ee7b666905b119ba93ee",
    template_id: 2,
    template_name: "Dog and Cat Shelter Website",
    desciption:
      "The non-profit organisation “Adopt Happiness” takes dogs and cats from the streets and provides shelter for them until they find an ideal home for them. They recently noticed a huge interest in adoption; however, they only have a Facebook page which makes applications long and very often confusing as they need to exchange a lot of messages with potential adopters. “Adopt Happiness” is looking to have its website where it could share photos of animals that are available for adoption, including the requirements for an ideal home. In addition, every interested applicant would be able to fill out an application which would make it easier for the organization to filter out unsuitable candidates based on each animal’s needs.",
    difficulty_rating: 9,
    time_esitmate: 2247248,
    team_estimate: 6,
  },
  {
    _id: "6357ee7b666905b119ba93ef",
    template_id: 3,
    template_name: "AND Eat",
    desciption:
      "Many ANDis are serious foodies. This means they often like to visit local restaurants to try out new cuisines. ANDis are also quite social so they like to be able to enjoy some equally good conversation alongside their meals.What I envisage is a portal which allows ANDis to inform other ANDis where they’re planing on going to lunch and what restaurants they recommend in the area. This portal would allow fellow foodies an opportunity to meet up and share their recommendations.",
    difficulty_rating: 9,
    time_esitmate: 3451682,
    team_estimate: 9,
  },
  {
    _id: "6357ee7b666905b119ba93f0",
    template_id: 1,
    template_name: "AND Hobby",
    desciption:
      "Our talented ANDIs have their favourite activities they like to do in their free time. Some like to bake, and others like doing crafts or enjoying outdoor and sports activities. Wouldn’t it be cool to be joined by another ANDi on your weekend hike? What I envisage is a portal where every ANDi can share his/her hobby, plan events and join and participate in events organized by other ANDis. This portal would allow ANDis to get to know each other and spend their free time doing favourite activities they have in common.",
    difficulty_rating: 4,
    time_esitmate: 4052701,
    team_estimate: 9,
  },
];